# Generated by Django 3.2.4 on 2021-08-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.TextField()),
                ('food_rate', models.DecimalField(decimal_places=1, max_digits='4')),
                ('food_desc', models.TextField()),
                ('food_type', models.CharField(choices=[('Veg', 'veg'), ('Non-Veg', 'non-veg'), ('jain', 'jain')], max_length=20)),
                ('food_cat', models.CharField(choices=[('Chinese', 'chinese'), ('South-Indian', 'south-indian'), ('Oriental', 'oriental'), ('Italian', 'italian'), ('Snacks', 'snacks'), ('Juices', 'juices')], max_length=20)),
            ],
        ),
    ]
